[project]
name = "03-orchestration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mlflow>=2.22.0",
    "polars>=1.30.0",
    "prefect>=3.4.3",
    "scikit-learn>=1.6.1",
]
